export const TOGGLEFOLD = "TOGGLEFOLD";
export const TOGGLESUBTASKSTATUS = "TOGGLESUBTASKSTATUS";
export const DELETESUBTASK = "DELETESUBTASK";
export const SAVESUBTASK = "SAVESUBTASK"; //save edited subtask
export const ADDSUBTASK = "ADDSUBTASK"; // add a new subtask
export const ADDTASK = "ADDTASK";
export const DELETETASK = "DELETETASK";
export const EDITTASK = "EDITTASK"; //edit and save a task
export const MOVEDOWN = "MOVEDOWN"; //move subtask up
export const MOVEUP = "MOVEUP"; //move subtask down
export const DRAG_SUBTASK = "DRAG_SUBTASK";
export const DROP_SUBTASK = "DROP_SUBTASK";
